version: "3.9"

services:
  hapi:
    image: hapiproject/hapi:latest
    ports: ["8080:8080"]
    environment:
      - HAPI_FHIR_VERSION=R5
    volumes:
      - hapi_data:/hapi/data
    # healthcheck:
    #   test: ["CMD-SHELL", "test -f /app/main.war && echo 'HAPI FHIR server is running'"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 60s

  pdfsvc:
    build: ./pdf_service
    ports: ["7001:7000"]
    volumes:
      - ./data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  empi:
    build: ./empi_mock
    ports: ["7002:7001"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  agent:
    build: ./agent_app
    env_file: .env
    volumes:
      - ./data:/app/data
      - ./tools.yml:/app/tools.yml
    depends_on:
      hapi:
        condition: service_started
      pdfsvc:
        condition: service_healthy
      empi:
        condition: service_healthy
    environment:
      - PYTHONPATH=/app
      - DATA_DIR=/app/data
    restart: unless-stopped
    command: sh -c "sleep 30 && python main.py"

volumes:
  hapi_data: 